In [2]:
import numpy as np

In [3]:
array_a = np.arange(0,100,2).reshape(5,10)
print(array_a)

[[ 0  2  4  6  8 10 12 14 16 18]
 [20 22 24 26 28 30 32 34 36 38]
 [40 42 44 46 48 50 52 54 56 58]
 [60 62 64 66 68 70 72 74 76 78]
 [80 82 84 86 88 90 92 94 96 98]]


In [ ]:
array_b = array_a