In [1]:
import numpy as np

In [3]:
array_a = np.array([[1, 2, 3],[4, 5, 6]])
print(array_a.shape)
print(array_a.size)

(2, 3)
6


In [20]:
array_resh = array_a.reshape(3,2)
print(array_resh)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
array_trans = array_a.T
print(array_trans)

[[1 4]
 [2 5]
 [3 6]]


In [18]:
print(array_trans[0])
print(array_trans[:,0])
print(array_trans[2,1])
print()
print(array_trans)

[1 4]
[1 2 3]
6

[[1 4]
 [2 5]
 [3 6]]
