In [1]:
import numpy as np

In [3]:
array_a = np.array([[1,2,3],[4,5,6]], dtype=str)
print(array_a)

[['1' '2' '3']
 ['4' '5' '6']]


In [4]:
array_b = np.zeros((3,3))
print(array_b)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [5]:
array_c = np.ones((3,3))
print(array_c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [7]:
array_d = np.full((3,3), 10)
print(array_d)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [9]:
array_e = np.random.randn((3,4))
print(array_e)

[[-0.82424267  1.79890003 -0.21900556 -0.94191385]
 [-0.40736562 -0.95243263  0.94363948  0.47913555]
 [ 0.04838029  0.40133266 -0.74890047  1.02895151]]


In [13]:
array_f = np.random.random((2,5))
print(array_f)

[[0.3944258  0.07631763 0.4239045  0.38351848 0.67434091]
 [0.24125831 0.8217893  0.63481081 0.51312087 0.66632436]]
