In [2]:
import numpy as np

In [3]:
r1 = [1,2,3,4,5]
r2 = [6,7,8,9,10]
r3 = [11,12,13,14,15]
r4 = [16,17,18,19,20]
r5 = [21,22,23,24,25]

data_test = np.array([r1,r2,r3,r4,r5])
print(data_test)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [10]:
# slice
print(data_test[:,1:4:1]) #start : ending value : step size
# negative index
print(data_test[:,-2:-4:-1])

[[ 2  3  4]
 [ 7  8  9]
 [12 13 14]
 [17 18 19]
 [22 23 24]]
[[ 4  3]
 [ 9  8]
 [14 13]
 [19 18]
 [24 23]]


In [11]:
# boolean
greater_than_ten = data_test > 10
print(greater_than_ten)

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [12]:
print(data_test[greater_than_ten])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [13]:
# where
drop_under_10_array = np.where(data_test > 10, data_test, 0)
print(drop_under_10_array)

[[ 0  0  0  0  0]
 [ 0  0  0  0  0]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
# logical_and
drop_under_10_and_over_16 = np.logical_and(data_test > 10, data_test < 16)
print(drop_under_10_and_over_16)

[[False False False False False]
 [False False False False False]
 [ True  True  True  True  True]
 [False False False False False]
 [False False False False False]]


In [27]:
print(data_test[drop_under_10_and_over_16])

[11 12 13 14 15]
